### ISSUE TITLE
Copyright Songs

### ISSUE THREAD

**Issue by CakeDevelopment** [Xogy/xsound#14]
How can i listen to Copyrighted songs... The most songs are copyrighted wich means i cant even use this library

**Comment by Xogy** [comment]
> How can i listen to Copyrighted songs... The most songs are copyrighted wich means i cant even use this library

Maybe update the xsound?

**Comment by Xogy** [comment]
Well anyway, update xsound and it will work fine.

if you can't update because you have "crewPhone" a phone that can play music from youtube, look in the config for addon list and switch the value from false to true & copy, paste the music files from "his" version.

There won't be any further support because if you cannot drag and drop files + switch from false to true
