### ISSUE TITLE
Text to speech does not work

### ISSUE THREAD

**Issue by Fatichti** [Xogy/xsound#35]
**Describe the bug**
I would like to use the TTS functionality but it does not work. There is no sound coming out.

**To Reproduce**
1. Start the resource: start xsound
2. Call the TTS function :  
```lua
function playTextToSpeech()
    print("DEBUG Trains : Play TTS")
    text = "toto"
    exports.xsound:TextToSpeechPos("testTTS", "en-FR", text, Config.VolumeSon, Config.Location)    -- where Config.VolumeSound = 0.5 and Config.Location a location in vector3
end
``` 
4. Launch the function : `playTextToSpeech()`
5. No error in the console but no spells

**Expected behavior**
A voice that orally says my typed text.

**Screenshots**
Nothing to show for it

**Additional context**
I tested the parameters like coordinates and location with the PlayUrlPos function and it works very well by putting a URL.

Also, copying the generated URL from the TTS and pasting it on a browser, it does sound good coming out as a google voice.
But impossible to hear the result in the game.

**Comment by Xogy** [comment]
https://github.com/Xogy/xsound/commit/2d67659829c693f6766e14ce4a4392ba35cb5f82

It was removed because google edited something which resulted in TTS stop working. I tried some free APIs but without luck.

Most likely google stopped supporting iframe access so the possible "fix" is to use some paid TTS API or try to find a free one that can generate ".mp3 / any sound format" direct url.

**Comment by Fatichti** [comment]
Maybe but why the URL is working when we test it on a brower ?
