### ISSUE TITLE
xsound server lua PlayUrlPos(source, name, url, volume, position, loop) calls not working

### ISSUE THREAD

**Issue by reinhardjs** [Xogy/xsound#59]
**Describe the bug**
I tried to call xsound from my server lua. the method I tried is PlayUrl and PlayUrlPos.
It doesn't even play the sound or in other words, not working at all.
It produces an error on the client console.

**To Reproduce**
1. Call PlayUrl or PlayUrlPos on server.lua
2. add print('something') into xsound's server resource it self
3. then look on in game console (press F8), then look at the screenshots i attached below

**Expected behavior**
I expected the xsound working on the server side.
Because i want to run xsound instance position updates only happen in server side.
I want to attach sound into npc ped, so everytime the ped moved, it also update the xsound instance position.

**Screenshots**
![image](https://github.com/Xogy/xsound/assets/7758970/a5ecf15e-f896-4cb3-8f1b-c2039e6e58a1)

**Suggested Solution**
- Pass the missing arguments `source` into the parameter
![image](https://github.com/Xogy/xsound/assets/7758970/58721b9f-1e4d-4b44-ad8c-2392124f78fb)

**Comment by reinhardjs** [comment]
We should just keeo our focus on fixing this part.
Because the left part implementation is incorrect.

**We should use table initialization like on the right side.**

Because, if we used the left side, the listener keep receiving nil value. 
So use the right side table initialization instead of the left then pass it to the `TriggerClientEvent("xsound:stateSound".....)`

![image](https://github.com/Xogy/xsound/assets/7758970/8b5ec3e6-3ec3-4c47-a97c-8a55f41e7357)

**Comment by Xogy** [comment]
You simply misunderstand how the function "TriggerClientEvent" works the arguments are following

(eventName, playerSourceID, ....)

I recommend checking out first docs for the triggerClientEvent

https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/TriggerClientEvent/

Just in case I did testing if it wasn't working and it is not the case, most likely your implementation of the API is just wrong.

![image](https://github.com/Xogy/xsound/assets/49158267/a758b617-59d2-498c-bb7e-254ae699f2e9)
![image](https://github.com/Xogy/xsound/assets/49158267/11a49829-8a14-4960-9a12-f9956eff128b)
![image](https://github.com/Xogy/xsound/assets/49158267/8d4d9ac0-4dc7-4d84-b6f8-99c46fa20877)
![image](https://github.com/Xogy/xsound/assets/49158267/ba20f586-5007-4b5c-b22d-742de3a7a070)


So I will be closing your PR since it is working without editing anything else.

**Comment by Xogy** [comment]
![image](https://github.com/Xogy/xsound/assets/49158267/b64d1488-3c03-4272-a49b-5b01be8146aa)
![image](https://github.com/Xogy/xsound/assets/49158267/35f6d564-783f-41cd-bd29-6d7b66b290ce)

Also based on the error it looks like you have nil value for "name"

**Comment by reinhardjs** [comment]
I tested it on DLC level 2944
![image](https://github.com/Xogy/xsound/assets/7758970/40279513-7005-449b-932d-3243c34c334b)

**Comment by reinhardjs** [comment]
> ![image](https://private-user-images.githubusercontent.com/49158267/333822716-b64d1488-3c03-4272-a49b-5b01be8146aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjAzNzgsIm5iZiI6MTcxNjY2MDA3OCwicGF0aCI6Ii80OTE1ODI2Ny8zMzM4MjI3MTYtYjY0ZDE0ODgtM2MwMy00MjcyLWE0OWItNWIwMWJlODE0NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMTk3NmJhNWU1NTliYTI1OTUzNWZlZjYxOTNkMTNhMmViYzFhZjFmNGI0Y2M0M2IzNWM3YWQ1OWJhY2Q3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wt2H6-159OC41cnVOPk5rnbZAZHdy3OdU4D375-JWbY) ![image](https://private-user-images.githubusercontent.com/49158267/333822780-35f6d564-783f-41cd-bd29-6d7b66b290ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjAzNzgsIm5iZiI6MTcxNjY2MDA3OCwicGF0aCI6Ii80OTE1ODI2Ny8zMzM4MjI3ODAtMzVmNmQ1NjQtNzgzZi00MWNkLWJkMjktNmQ3YjY2YjI5MGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MjhiMTBjMDAzYTJmNGQ4YmJjODM1M2UwZGFlNGEyZjk3Y2YxYzQ3MTBlYWQ3ODQ0YmJkYTZlMGM0ZmE1YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-Wbfs-GrMM02zCcDg6dJ7LI3hgVeVj_sfMTmCTv2Nc)
> 
> Also based on the error it looks like you have nil value for "name"

No, actually, I have made sure that nothing is nil first. Trust me, it is an issue 😅. 
You can try logging both on the client listener and at the place where the server triggers.

If you find it to be a bug, could you consider reopening my pull request?

**Comment by reinhardjs** [comment]
> I mistakenly omitted the first parameter, `source`, on to the `TriggerClientEvent`. It shouldn't be the first parameter, so I added a commit to revert it. After that, all my fixes were working correctly.

I mistakenly omitted the first parameter, source, on to the TriggerClientEvent. It shouldn't be the first parameter, so I added a commit to revert it. After that, all my fixes were working correctly.

> **Describe the bug** I tried to call xsound from my server lua. the method I tried is PlayUrl and PlayUrlPos. It doesn't even play the sound or in other words, not working at all. It produces an error on the client console.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Call PlayUrl or PlayUrlPos on server.lua
> 2. add print('something') into xsound's server resource it self
> 3. then look on in game console (press F8), then look at the screenshots i attached below
> 4. See error
> 
> **Expected behavior** I expected the xsound working on the server side. Because i want to run xsound instance position updates only happen in server side. I want to attach sound into npc ped, so everytime the ped moved, it also update the xsound instance position.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/7758970/333810813-a5ecf15e-f896-4cb3-8f1b-c2039e6e58a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjEyNjcsIm5iZiI6MTcxNjY2MDk2NywicGF0aCI6Ii83NzU4OTcwLzMzMzgxMDgxMy1hNWVjZjE1ZS1mODk2LTRjYjMtOGYxYi1jMjAzOWU2ZTU4YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTgxNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmRkNWJiZDVhMDI0MWM4MDA1MzQ0YjY4NTJiZWVjZjZlNDgxZjU5OTRhOTk2YWQzYmFhNzcwYmNkNDJhZjE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4FXw7JRQKL-Nk8-UUu0NH16qR6DpCQsIqFFV8wULgEM)
> 
> **Suggested Solution**
> 
> * Change the way of sending data to the RegisterNetEvent listener on the client.

I mistakenly omitted the first parameter, source, on to the TriggerClientEvent. It shouldn't be the first parameter, so I added a commit to revert it. After that, all my fixes were working correctly.

**Comment by reinhardjs** [comment]
> ![image](https://private-user-images.githubusercontent.com/49158267/333822716-b64d1488-3c03-4272-a49b-5b01be8146aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjEyNjcsIm5iZiI6MTcxNjY2MDk2NywicGF0aCI6Ii80OTE1ODI2Ny8zMzM4MjI3MTYtYjY0ZDE0ODgtM2MwMy00MjcyLWE0OWItNWIwMWJlODE0NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYjVmOTNhODYxYjZmNTEyZjNlMTAyMzBjMDk0MjQyNzEyYzYyMzU1OGMyZmIxOWE2ZTE1MTczNDk4ZDUyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a9IqYDrlSMcLfNG1YpXbljPyMTF7HwwEDDL6Ipzq_TM) ![image](https://private-user-images.githubusercontent.com/49158267/333822780-35f6d564-783f-41cd-bd29-6d7b66b290ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NjEyNjcsIm5iZiI6MTcxNjY2MDk2NywicGF0aCI6Ii80OTE1ODI2Ny8zMzM4MjI3ODAtMzVmNmQ1NjQtNzgzZi00MWNkLWJkMjktNmQ3YjY2YjI5MGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDE4MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OWQwYmQ1ZDMzMzc1MjU3M2RkYmZmNTVlNzk3YWVlMjY1NmZlODdjZGEwOGY4Yjk3YTk5NGQ5ZGEwNjQ2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HodsmvxtWtFTyYesjCxhTMrKCTX0qqn0fcXFSyOsi3k)
> 
> Also based on the error it looks like you have nil value for "name"

No, actually, I have made sure that nothing is nil first. Trust me, it is an issue 😅.
You can try logging both on the client listener and at the place where the server triggers.

If you find it to be a bug, could you consider reopening my pull request?

**Comment by reinhardjs** [comment]
You can watch how I tested it here:
https://youtu.be/UbGrjPFx_hk?t=15888

**Comment by reinhardjs** [comment]
You can watch how I tested it here:
https://youtu.be/UbGrjPFx_hk?t=15888

@Xogy

**Comment by reinhardjs** [comment]
You can watch how I tested it here:
https://youtu.be/UbGrjPFx_hk?t=15996

@Xogy

**Comment by Xogy** [comment]
> You can watch how I tested it here: https://youtu.be/UbGrjPFx_hk?t=15996
> 
> @Xogy

![image](https://github.com/Xogy/xsound/assets/49158267/a316f7c4-cdde-4922-a1fd-82e4087e8286)

yes I do see and this proves the point I mentioned above that the "name" is nil

Also based on the code + error message you have in your console here

![image](https://github.com/Xogy/xsound/assets/49158267/7c91485e-ddb4-4074-86e0-3f37295d5250)
![image](https://github.com/Xogy/xsound/assets/49158267/43275c0c-9a63-4b93-b0ae-09ce044819ac)


Neither the first or second arguments have any value meaning they're nil values. ( for some reason you kept changing during the stream the "source" for string, double, and number) but even an hour later ( fast skip ) the name argument is still not being initialized anywhere.

![image](https://github.com/Xogy/xsound/assets/49158267/f502f1bc-6b2b-48be-b96c-4c5fc3c19b89)
at 4 hours and 16 minutes, you changed the argument from non-existent to something that has already value but unfortunately because of the extra argument "source" in the "RegisterNetEvent" it didn't have any value.

You can just do a simple debug of arguments and it will tell you which arguments have what values.

Correct values should be this
- number
- string
- string
- double
- vector3
- bool
```LUA
function PlayUrlPos(source, name_, url_, volume_, pos, loop_)
    print("PlayUrlPos", source, name_, url_, volume_, pos, loop_)
    TriggerClientEvent("xsound:stateSound", source, "playpos", {
        soundId = name_,
        position = pos,
        url = url_,
        volume = volume_,
        loop = loop_
    })
end
```

Anything else is wrong.

The PR you made is pretty much the same code just in different colors there are no differences between what you did with the table vs what I have done. 

So I simply won't be accepting it because as I mentioned the implementation was simply wrong.


ChatGPT isn't always a reliable way how to do things, you always have to verify the output it gives you.


Everyone makes mistakes it happens I do too. But this is not xsound fault but your implementation which I already showed you above what was wrong and what have you fixed.

With this, I don't see any reason to contribute more to this conversation
